### ISSUE TITLE
doesn't work on 1.12.2

### ISSUE THREAD

**Issue by Hakker** [alothmanmoe/ForgeAutoShutdown#1]
[12:22:34] [Server thread/DEBUG] [FML]: Examining file forgeautoshutdown-1.10.2-1.0.8.jar for potential mods
[12:22:34] [Server thread/TRACE] [FML]: Located mcmod.info file in file forgeautoshutdown-1.10.2-1.0.8.jar
[12:22:34] [Server thread/DEBUG] [FML]: Identified a mod of type Lnet/minecraftforge/fml/common/Mod; (roycurtis.autoshutdown.ForgeAutoShutdown) - loading
[12:22:34] [Server thread/ERROR] [FML]: Unable to construct net.minecraftforge.fml.common.Mod container
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_171]
	at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:73) [ModContainerFactory.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:114) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:425) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: The modId ForgeAutoShutdown must be all lowercase.
	at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:145) ~[FMLModContainer.class:?]
	at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:129) ~[FMLModContainer.class:?]
	... 16 more

**Comment by alothmanmoe** [comment]
Hello, yes the mod is intended for 1.10.2, there is no update for 1.12.2 at the moment

**Comment by Hakker** [comment]
> Made for Forge 1.7.10, 1.8, and 1.10.2-1.12.2

It's mentioned as such on Curseforge. That said I hope it will get an update it's a small but handy thing especially on windows where task scheduler can act a little bit strange in the long run.

**Comment by alothmanmoe** [comment]
That's a mistake on my end, 1.12 is coming soon but i have just not had the time to work on it

**Comment by sandtechnology** [comment]
Not sure if it was so long for replying, but I just port this mod to 1.12.2, feel free to use it!

Source code: https://github.com/sandtechnology/ForgeAutoShutdown

Download there: https://github.com/sandtechnology/ForgeAutoShutdown/releases/download/1.0.1/forgeautoshutdown-1.12.2-1.0.jar
